"""empty message

Revision ID: 99159d5cb96e
Revises: 
Create Date: 2018-05-14 16:27:54.790171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99159d5cb96e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('shortLink', sa.TEXT(), nullable=False),
    sa.Column('longLink', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('ip', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('shortLink')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url')
    # ### end Alembic commands ###
